import React, { useEffect, useState, useCallback } from 'react';
import { campaignAPI, segmentAPI } from '../../services/api';
import { useToast } from '../../context/ToastContext';
import {
  PageHeader, Button, Input, Select, Table, Modal,
  Badge, Spinner, EmptyState, StatBar
} from '../../components/common';

const CHANNELS = ['WhatsApp','SMS','Email','RCS'];

const statusColor = s => ({ completed:'green', sent:'blue', sending:'amber', draft:'gray', failed:'red' }[s]||'gray');

export default function Campaigns() {
  const [campaigns, setCampaigns] = useState([]);
  const [segments,  setSegments]  = useState([]);
  const [loading,   setLoading]   = useState(true);
  const [modal,     setModal]     = useState(null);
  const [detail,    setDetail]    = useState(null);
  const [form,      setForm]      = useState({ name:'', segment_id:'', channel:'WhatsApp', message:'', ai_generated:0 });
  const [saving,    setSaving]    = useState(false);
  const [sending,   setSending]   = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const toast = useToast();

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [c,s] = await Promise.all([campaignAPI.list(), segmentAPI.list()]);
      setCampaigns(c.data);
      setSegments(s.data);
    } finally { setLoading(false); }
  }, []);

  useEffect(() => { load(); }, [load]);

  const openCreate = () => {
    setForm({ name:'', segment_id: segments[0]?.segment_id||'', channel:'WhatsApp', message:'' });
    setModal('create');
  };

  const openDetail = async (c) => {
    const r = await campaignAPI.get(c.campaign_id);
    setDetail(r.data);
    setModal('detail');
  };

  const aiGenMessage = async () => {
    if (!form.segment_id) return toast('Select a segment first','warning');
    setAiLoading(true);
    try {
      const seg = segments.find(s=>s.segment_id===form.segment_id);
      const r = await campaignAPI.aiMessage({
        channel: form.channel, segment_id: form.segment_id,
        goal: 'increase engagement and drive sales',
      });
      setForm(f => ({ ...f, message: r.data.message, ai_generated: 1 }));
      toast('Message generated by AI ✨');
    } catch(e) { toast(e.message,'error'); }
    finally { setAiLoading(false); }
  };

  const save = async () => {
    setSaving(true);
    try {
      await campaignAPI.create(form);
      toast('Campaign created');
      setModal(null); load();
    } catch(e) { toast(e.message,'error'); }
    finally { setSaving(false); }
  };

  const send = async (id) => {
    setSending(id);
    try {
      const r = await campaignAPI.send(id);
      toast(`Sending to ${r.data.count} customers 🚀`);
      load();
    } catch(e) { toast(e.message,'error'); }
    finally { setSending(null); }
  };

  const columns = [
    { key:'name',         header:'Campaign', render:(v,r)=>(
      <div>
        <div className="font-medium text-white flex items-center gap-1">
          {v} {r.ai_generated ? <span className="text-xs text-purple-400">✦</span> : ''}
        </div>
        <div className="text-xs text-muted">{r.segment_name}</div>
      </div>
    )},
    { key:'channel', header:'Channel', render:v=><Badge color="blue">{v}</Badge> },
    { key:'status',  header:'Status',  render:v=><Badge color={statusColor(v)}>{v}</Badge> },
    { key:'stat_sent',      header:'Sent',      render:v=><span className="text-muted">{v}</span> },
    { key:'stat_delivered', header:'Delivered', render:v=><span className="text-muted">{v}</span> },
    { key:'stat_clicked',   header:'Clicked',   render:v=><span className="text-brand-300">{v}</span> },
    { key:'stat_converted', header:'Converted', render:v=><span className="text-emerald-300">{v}</span> },
    {
      key:'campaign_id', header:'Actions',
      render:(_,r)=>(
        <div className="flex gap-2" onClick={e=>e.stopPropagation()}>
          {r.status==='draft' && (
            <button onClick={()=>send(r.campaign_id)}
              disabled={!!sending}
              className="text-xs bg-emerald-500/20 text-emerald-300 hover:bg-emerald-500/30 px-2.5 py-1 rounded-lg transition-colors">
              {sending===r.campaign_id ? '…' : '▶ Send'}
            </button>
          )}
        </div>
      ),
    },
  ];

  return (
    <div className="p-6 max-w-7xl mx-auto">
      <PageHeader
        title="Campaigns"
        subtitle={`${campaigns.length} total campaigns`}
        actions={<Button onClick={openCreate}>+ New Campaign</Button>}
      />

      {loading ? <Spinner /> : (
        campaigns.length === 0 ? (
          <EmptyState icon="📢" title="No campaigns yet"
            description="Create your first campaign and start engaging customers"
            action={<Button onClick={openCreate}>Create Campaign</Button>} />
        ) : (
          <Table columns={columns} data={campaigns} onRowClick={openDetail} />
        )
      )}

      {/* Create Modal */}
      <Modal open={modal==='create'} onClose={()=>setModal(null)} title="New Campaign" maxWidth="max-w-2xl">
        <div className="space-y-4">
          <Input label="Campaign Name *" value={form.name}
            onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="Summer Sale Blast" />

          <Select label="Audience Segment *" value={form.segment_id}
            onChange={e=>setForm(f=>({...f,segment_id:e.target.value}))}>
            <option value="">Select segment…</option>
            {segments.map(s=><option key={s.segment_id} value={s.segment_id}>{s.name} ({s.customer_count})</option>)}
          </Select>

          <Select label="Channel *" value={form.channel}
            onChange={e=>setForm(f=>({...f,channel:e.target.value}))}>
            {CHANNELS.map(c=><option key={c}>{c}</option>)}
          </Select>

          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs font-medium text-muted">Message *</label>
              <Button variant="ai" size="sm" onClick={aiGenMessage} loading={aiLoading}>
                ✦ Generate with AI
              </Button>
            </div>
            {form.ai_generated === 1 && (
              <div className="text-xs text-purple-400 mb-1 flex items-center gap-1">✦ AI-generated message</div>
            )}
            <textarea
              rows={4}
              value={form.message}
              onChange={e=>setForm(f=>({...f,message:e.target.value,ai_generated:0}))}
              placeholder="Hi {name}, we have an exclusive offer for you…"
              className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-white
                placeholder-muted focus:outline-none focus:border-brand-500 resize-none"
            />
          </div>

          <div className="flex gap-2 pt-2">
            <Button onClick={save} loading={saving} className="flex-1">Create Campaign</Button>
            <Button variant="secondary" onClick={()=>setModal(null)}>Cancel</Button>
          </div>
        </div>
      </Modal>

      {/* Detail Modal */}
      {detail && (
        <Modal open={modal==='detail'} onClose={()=>{ setModal(null); setDetail(null); }}
          title={detail.name} maxWidth="max-w-2xl">
          <div className="space-y-4">
            <div className="flex gap-2 flex-wrap">
              <Badge color="blue">{detail.channel}</Badge>
              <Badge color={statusColor(detail.status)}>{detail.status}</Badge>
              {detail.ai_generated ? <Badge color="purple">✦ AI message</Badge> : null}
            </div>
            <div className="bg-surface rounded-xl p-4">
              <div className="text-xs text-muted mb-1">Message</div>
              <div className="text-sm text-white">{detail.message}</div>
            </div>
            <div className="grid grid-cols-3 gap-3">
              {[
                ['Sent',      detail.stat_sent,      'text-white'],
                ['Delivered', detail.stat_delivered, 'text-blue-300'],
                ['Failed',    detail.stat_failed,    'text-rose-300'],
                ['Opened',    detail.stat_opened,    'text-amber-300'],
                ['Clicked',   detail.stat_clicked,   'text-brand-300'],
                ['Converted', detail.stat_converted, 'text-emerald-300'],
              ].map(([l,v,c])=>(
                <div key={l} className="bg-white/5 rounded-xl p-3 text-center">
                  <div className={`text-xl font-bold ${c}`}>{v}</div>
                  <div className="text-xs text-muted">{l}</div>
                </div>
              ))}
            </div>
            <div>
              <div className="text-xs font-medium text-muted mb-3">Delivery Funnel</div>
              <div className="space-y-2">
                <StatBar label="Delivered" value={detail.stat_delivered} max={detail.stat_sent} color="bg-brand-500" />
                <StatBar label="Opened"    value={detail.stat_opened}    max={detail.stat_sent} color="bg-purple-500" />
                <StatBar label="Clicked"   value={detail.stat_clicked}   max={detail.stat_sent} color="bg-amber-500" />
                <StatBar label="Converted" value={detail.stat_converted} max={detail.stat_sent} color="bg-emerald-500" />
              </div>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
}
